/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

// 创建一个包装器来处理动态导入错误
function createAsyncComponent(importFn: () => Promise<any>, fallbackPath?: string) {
  return async () => {
    try {
      return await importFn();
    } catch (error) {
      console.error('Failed to load component:', error);
      
      // 停止loading状态
      if (window.NProgress) {
        window.NProgress.done();
      }
      
      // 如果有fallback路径，尝试加载fallback组件
      if (fallbackPath) {
        try {
          return await import(/* @vite-ignore */ fallbackPath);
        } catch (fallbackError) {
          console.error('Failed to load fallback component:', fallbackError);
        }
      }
      
      // 最后的fallback: 404组件
      return import(/* @vite-ignore */ "@/views/_builtin/404/index.vue");
    }
  };
}

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: createAsyncComponent(() => import("@/views/_builtin/403/index.vue")),
  404: createAsyncComponent(() => import("@/views/_builtin/404/index.vue")),
  500: createAsyncComponent(() => import("@/views/_builtin/500/index.vue")),
  "blog-manage": createAsyncComponent(() => import("@/views/blog-manage/index.vue"), "@/views/_builtin/404/index.vue"),
  "gensiblog-preview": createAsyncComponent(() => import("@/views/gensiblog-preview/index.vue"), "@/views/_builtin/404/index.vue"),
  "gensiblog-manage": createAsyncComponent(() => import("@/views/gensiblog-manage/index.vue"), "@/views/_builtin/404/index.vue"),
  "followus": createAsyncComponent(() => import("@/views/followus/index.vue"), "@/views/_builtin/404/index.vue"),
  "group-manage": createAsyncComponent(() => import("@/views/group-manage/index.vue"), "@/views/_builtin/404/index.vue"),
  "iframe-page": createAsyncComponent(() => import("@/views/_builtin/iframe-page/[url].vue")),
  login: createAsyncComponent(() => import("@/views/_builtin/login/index.vue")),

  "member-manage": createAsyncComponent(() => import("@/views/member-manage/index.vue"), "@/views/_builtin/404/index.vue"),
  "message-view": createAsyncComponent(() => import("@/views/message-view/index.vue"), "@/views/_builtin/404/index.vue"),
  "news-manage": createAsyncComponent(() => import("@/views/news-manage/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_about: createAsyncComponent(() => import("@/views/portal/about/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_contact: createAsyncComponent(() => import("@/views/portal/contact/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_home: createAsyncComponent(() => import("@/views/portal/home/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_news: createAsyncComponent(() => import("@/views/portal/news/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_article: createAsyncComponent(() => import("@/views/portal/article/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_posts: createAsyncComponent(() => import("@/views/portal/posts/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_research: createAsyncComponent(() => import("@/views/portal/research/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_publications: createAsyncComponent(() => import("@/views/portal/publications/index.vue"), "@/views/_builtin/404/index.vue"),
  "project-manage": createAsyncComponent(() => import("@/views/project-manage/index.vue"), "@/views/_builtin/404/index.vue"),
  "publish-manage": createAsyncComponent(() => import("@/views/publish-manage/index.vue"), "@/views/_builtin/404/index.vue"),
  "alumni": createAsyncComponent(() => import("@/views/alumni/index.vue"), "@/views/_builtin/404/index.vue"),
  description: createAsyncComponent(() => import("@/views/description/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_postdetail: createAsyncComponent(() => import("@/views/portal/postdetail/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_gallery: createAsyncComponent(() => import("@/views/portal/gallery/index.vue"), "@/views/_builtin/404/index.vue"),
  slideshow: createAsyncComponent(() => import("@/views/slideshow/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_project: createAsyncComponent(() => import("@/views/portal/project/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_blog: createAsyncComponent(() => import("@/views/portal/blog/index.vue"), "@/views/_builtin/404/index.vue"),
  portal_blogdetail: createAsyncComponent(() => import("@/views/portal/blogdetail/index.vue"), "@/views/_builtin/404/index.vue"),
};
