/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'blog-manage',
    path: '/blog-manage',
    component: 'layout.base$view.blog-manage',
    meta: {
      title: 'blog-manage',
      i18nKey: 'route.blog-manage',
      icon: 'material-symbols:article',
      order: 6
    }
  },
  {
    name: 'gensiblog-preview',
    path: '/gensiblog-preview',
    component: 'layout.blank$view.gensiblog-preview',
    meta: {
      title: 'Gensiblog Preview',
      i18nKey: 'route.gensiblog-manage',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'gensiblog-manage',
    path: '/gensiblog-manage',
    component: 'layout.base$view.gensiblog-manage',
    meta: {
      title: 'gensiblog-manage',
      i18nKey: 'route.gensiblog-manage',
      icon: 'material-symbols:article-outline',
      order: 7
    }
  },
  {
    name: 'followus',
    path: '/followus',
    component: 'layout.base$view.followus',
    meta: {
      title: 'followus',
      i18nKey: 'route.followus',
      icon: 'material-symbols:favorite',
      order: 3
    }
  },
  // {
  //   name: 'group-manage',
  //   path: '/group-manage',
  //   component: 'layout.base$view.group-manage',
  //   meta: {
  //     title: 'group-manage',
  //     i18nKey: 'route.group-manage',
  //     icon: 'material-symbols:groups',
  //     order: 8
  //   }
  // },

  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'member-manage',
    path: '/member-manage',
    component: 'layout.base$view.member-manage',
    meta: {
      title: 'member-manage',
      i18nKey: 'route.member-manage',
      icon: 'material-symbols:group',
      order: 7
    }
  },
  {
    name: 'message-view',
    path: '/message-view',
    component: 'layout.base$view.message-view',
    meta: {
      title: 'message-view',
      i18nKey: 'route.message-view',
      icon: 'material-symbols:chat',
      order: 10
    }
  },
  {
    name: 'news-manage',
    path: '/news-manage',
    component: 'layout.base$view.news-manage',
    meta: {
      title: 'news-manage',
      i18nKey: 'route.news-manage',
      icon: 'material-symbols:newspaper',
      order: 5
    }
  },
  {
    name: 'portal_about',
    path: '/portal/about',
    component: 'layout.blank$view.portal_about',
    meta: {
      title: 'About - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'portal_contact',
    path: '/portal/contact',
    component: 'layout.blank$view.portal_contact',
    meta: {
      title: 'Contact - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'portal_home',
    path: '/portal_home',
    component: 'layout.blank$view.portal_home',
    meta: {
      title: 'Home - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'portal_news',
    path: '/portal/news',
    component: 'layout.blank$view.portal_news',
    meta: {
      title: 'News - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'portal_article',
    path: '/portal/article',
    component: 'layout.blank$view.portal_article',
    meta: {
      title: 'Articles - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'portal_posts',
    path: '/portal/posts',
    component: 'layout.blank$view.portal_posts',
    meta: {
      title: 'Posts - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'portal_postdetail',
    path: '/portal/postdetail',
    component: 'layout.blank$view.portal_postdetail',
    meta: {
      title: 'Post Detail - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },                  
  {
    name: 'portal_research',
    path: '/portal/research',
    component: 'layout.blank$view.portal_research',
    meta: {
      title: 'Research - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'portal_publications',
    path: '/portal/publications',
    component: 'layout.blank$view.portal_publications',
    meta: {
      title: 'Publications - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'portal_project',
    path: '/portal/project',
    component: 'layout.blank$view.portal_project',
    meta: {
      title: 'Projects - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'portal_blog',
    path: '/portal/blog',
    component: 'layout.blank$view.portal_blog',
    meta: {
      title: 'Blog - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'portal_blogdetail',
    path: '/portal/:routename/:id',
    component: 'layout.blank$view.portal_blogdetail',
    meta: {
      title: 'Blog Detail - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'portal_gallery',
    path: '/portal/gallery',
    component: 'layout.blank$view.portal_gallery',
    meta: {
      title: 'Gallery - GenSI',
      i18nKey: 'route.GenSI',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'project-manage',
    path: '/project-manage',
    component: 'layout.base$view.project-manage',
    meta: {
      title: 'project-manage',
      i18nKey: 'route.project-manage',
      icon: 'material-symbols:folder-managed',
      order: 2
    }
  },
  {
    name: 'publish-manage',
    path: '/publish-manage',
    component: 'layout.base$view.publish-manage',
    meta: {
      title: 'publish-manage',
      i18nKey: 'route.publish-manage',
      icon: 'material-symbols:publish',
      order: 4
    }
  },
  {
    name: 'alumni',
    path: '/alumni',
    component: 'layout.base$view.alumni',
    meta: {
      title: 'alumni',
      i18nKey: 'route.alumni',
      icon: 'material-symbols:person-outline',
      order: 8
    }
  },
  {
    name: 'description',
    path: '/description',
    component: 'layout.base$view.description',
    meta: {
      title: 'description',
      i18nKey: 'route.description',
      icon: 'material-symbols:person-outline',
      order: 10
    }
  },
  {
    name: 'slideshow',
    path: '/slideshow',
    component: 'layout.base$view.slideshow',
    meta: {
      title: 'slideshow',
      i18nKey: 'route.slideshow',
      icon: 'material-symbols:slideshow',
      order: 1
    }
  },

];
